### ISSUE TITLE
[INFO] Semantic versioning per PR

### ISSUE THREAD

**Issue by sarahbx** [RedHatQE/openshift-python-wrapper#145]
As we are shifting to [semantic versioning](https://semver.org), we will start assigning major/minor/patch to each PR. This process is being defined, but each PR will be considered a release.

I want to highlight this one line in the spec:
> 3. Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.
> https://semver.org/#spec-item-3

Please be sure to review the FAQ it will answer most of your questions.
https://semver.org/#faq

**Comment by myakove** [comment]
Closing, we are not going to implement it.
We keep bound to OpenShift major versions for now.
