### ISSUE TITLE
[ISSUE] Resource.labels does not return a dict, returns a ResourceField

### ISSUE THREAD

**Issue by sarahbx** [RedHatQE/openshift-python-wrapper#174]
https://github.com/RedHatQE/openshift-python-wrapper/blob/a7a064c8e6b0c8106dd00c02a5c1048945272217/ocp_resources/resource.py#L708

```
>>> type(node.labels)
<class 'openshift.dynamic.resource.ResourceField'>
```
Does not fully support use as a dictionary, eg: `X in ResourceField` != `X in ResourceField.keys()`

**Comment by myakove** [comment]
@sarahbx 
We need the resource/part of resource as we get it.
If you need to access the dict do:
`dict(worker_node1.labels)`

```
ipdb> type(dict(worker_node1.labels))
<class 'dict'>

```
