### ISSUE TITLE
Revert "Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition" - 1782

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/openshift-python-wrapper#1783]
[Auto generated]
Number: [#1782]

**Comment by msi-b1** [comment]
[1;34mopenshift-python-wrapper[1;0m(XF86p)[PR 1782]: Closing issue for PR: Revert "Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition".
PR was closed.
