### ISSUE TITLE
Revert "CherryPicked: [v4.15] Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition" - 1784

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#1785]
[Auto generated]
Number: [#1784]

**Comment by redhat-qe-bot1** [comment]
[1;34mopenshift-python-wrapper[1;0m(8agTZ)[PR 1784]: Closing issue for PR: Revert "CherryPicked: [v4.15] Add vlan and mtu parameters to OVNOverlayNetworkAttachmentDefinition".
PR was closed.
