### ISSUE TITLE
Broken docs link in README

### ISSUE THREAD

**Issue by lobziik** [RedHatQE/openshift-python-wrapper#187]
**Describe the bug**
Link to documentation in README seems not actual.
https://redhatqe.github.io/openshift-python-wrapper/ocp_resources/index.html - shows 404.

**To Reproduce**
Click on doc link on the [frontpage](https://github.com/RedHatQE/openshift-python-wrapper) of this repository.

**Expected behavior**
Page with some meaningful content or no such references at all :)

**Comment by myakove** [comment]
Fixed, thanks for reporting.
