### ISSUE TITLE
update poetry to point to kubernetes 29.0.0 - 1895

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#1896]
[Auto generated]
Number: [#1895]

**Comment by redhat-qe-bot2** [comment]
[1;34mopenshift-python-wrapper[1;0m(99656650-3eca-11ef-89df-a6f7326ca14b)[PR 1895]: Closing issue for PR: update poetry to point to kubernetes 29.0.0.
PR was closed.
