### ISSUE TITLE
Remove manual run, the script needs running cluster to run - 1930

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#1931]
[Auto generated]
Number: [#1930]

**Comment by redhat-qe-bot2** [comment]
[38;5;106mopenshift-python-wrapper[0m[pull_request][4a7b-11ef-910b-920aac09127f][PR 1930]: Closing issue for PR: Remove manual run, the script needs running cluster to run.
PR was closed.
