### ISSUE TITLE
Refactored class_generator.py to remove debug logging and updated cla… - 1950

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#1951]
[Auto generated]
Number: [#1950]

**Comment by redhat-qe-bot1** [comment]
[38;5;236mopenshift-python-wrapper[0m[pull_request][4d82-11ef-8dcd-0f50cfab5889][PR 1950]: Closing issue for PR: Refactored class_generator.py to remove debug logging and updated cla….
PR was closed.
