### ISSUE TITLE
Update class_generator.py to handle output file name - 1962

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#1963]
[Auto generated]
Number: [#1962]

**Comment by redhat-qe-bot2** [comment]
[38;5;164mopenshift-python-wrapper[0m[pull_request][4d98-11ef-9fdf-e9e7cbd53712][PR 1962]: Closing issue for PR: Update class_generator.py to handle output file name.
PR was closed.
