### ISSUE TITLE
class_generator: Enable frop to pdb on error - 1970

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/openshift-python-wrapper#1971]
[Auto generated]
Number: [#1970]

**Comment by msi-b1** [comment]
[38;5;155mopenshift-python-wrapper[0m[pull_request][4db0-11ef-981e-7cf7119ddebf][PR 1970]: Closing issue for PR: class_generator: Enable frop to pdb on error.
PR was closed.
