### ISSUE TITLE
Update Containerized Data Importer (CDI) resource - 1977

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#1978]
[Auto generated]
Number: [#1977]

**Comment by redhat-qe-bot1** [comment]
[38;5;42mopenshift-python-wrapper[0m[pull_request][4f0f-11ef-9610-b30f390725ed][PR 1977]: Closing issue for PR: Update Containerized Data Importer (CDI) resource.
PR was closed.
