### ISSUE TITLE
Issues in generating tekton task resource class with class-generator

### ISSUE THREAD

**Issue by geetikakay** [RedHatQE/openshift-python-wrapper#2006]
**Describe the bug**
I make sure task exists in cluster .
$ oc get task -A
NAMESPACE             NAME                      AGE
openshift-pipelines   buildah                   4d11h
openshift-pipelines   git-cli                   4d11h
openshift-pipelines   git-clone                 4d11h
$ oc api-resources| grep task
clustertasks                                                                                                                 tekton.dev/v1beta1                             false        ClusterTask
taskruns                              tr,trs                                                                                 tekton.dev/v1                                  true         TaskRun
tasks                                                                                                                        tekton.dev/v1                                  true         Task

While running class-generator, script worked but resources are not generated well.

Debug report

task_debug.json
{
    "explain": "GROUP:      tekton.dev\nKIND:       Task\nVERSION:    v1\n\nDESCRIPTION:\n    <empty>\nFIELDS:\n  apiVersion\t<string>\n  kind\t<string>\n  metadata\t<ObjectMeta>\n    annotations\t<map[string]string>\n    creationTimestamp\t<string>\n    deletionGracePeriodSeconds\t<integer>\n    deletionTimestamp\t<string>\n    finalizers\t<[]string>\n    generateName\t<string>\n    generation\t<integer>\n    labels\t<map[string]string>\n    managedFields\t<[]ManagedFieldsEntry>\n      apiVersion\t<string>\n      fieldsType\t<string>\n      fieldsV1\t<FieldsV1>\n      manager\t<string>\n      operation\t<string>\n      subresource\t<string>\n      time\t<string>\n    name\t<string>\n    namespace\t<string>\n    ownerReferences\t<[]OwnerReference>\n      apiVersion\t<string> -required-\n      blockOwnerDeletion\t<boolean>\n      controller\t<boolean>\n      kind\t<string> -required-\n      name\t<string> -required-\n      uid\t<string> -required-\n    resourceVersion\t<string>\n    selfLink\t<string>\n    uid\t<string>\n\n",
    "namespace": "1\n"

}

$ cat ocp_resources/task.py
# Generated using https://github.com/RedHatQE/openshift-python-wrapper/blob/main/scripts/resource/README.md

from typing import Any
from ocp_resources.resource import NamespacedResource

class Task(NamespacedResource):
    """
    <empty>
    """

    api_group: str = NamespacedResource.ApiGroup.TEKTON_DEV

    def __init__(
        self,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Additional context**

**Comment by myakove** [comment]
The script use `oc explain` to get all needed info to generate the class.

Task kind is missing information:

```
❱ oc explain task --recursive                                                                                                                                                            
GROUP:      tekton.dev
KIND:       Task
VERSION:    v1

DESCRIPTION:
    <empty>
FIELDS:
  apiVersion    <string>
  kind  <string>
  metadata      <ObjectMeta>
    annotations <map[string]string>
    creationTimestamp   <string>
    deletionGracePeriodSeconds  <integer>
    deletionTimestamp   <string>
    finalizers  <[]string>
    generateName        <string>
    generation  <integer>
    labels      <map[string]string>
    managedFields       <[]ManagedFieldsEntry>
      apiVersion        <string>
      fieldsType        <string>
      fieldsV1  <FieldsV1>
      manager   <string>
      operation <string>
      subresource       <string>
      time      <string>
    name        <string>
    namespace   <string>
    ownerReferences     <[]OwnerReference>
      apiVersion        <string> -required-
      blockOwnerDeletion        <boolean>
      controller        <boolean>
      kind      <string> -required-
      name      <string> -required-
      uid       <string> -required-
    resourceVersion     <string>
    selfLink    <string>
    uid <string>
```
