### ISSUE TITLE
Do not generate class if description in explain in <empty> - 2007

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#2008]
[Auto generated]
Number: [#2007]

**Comment by redhat-qe-bot1** [comment]
[38;5;231mopenshift-python-wrapper[0m[pull_request][54a7-11ef-9195-2252e1a761fb][PR 2007]: Closing issue for PR: Do not generate class if description in explain in <empty>.
PR was closed.
