### ISSUE TITLE
Split FIELDS and SPEC in mandatory fields - 2015

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2016]
[Auto generated]
Number: [#2015]

**Comment by redhat-qe-bot2** [comment]
[38;5;90mopenshift-python-wrapper[0m[pull_request][5898-11ef-8462-5d6e0e4c1d7e][PR 2015]: Closing issue for PR: Split FIELDS and SPEC in mandatory fields.
PR was closed.
