### ISSUE TITLE
class-generator: Update and add cluster schema API files - 2037

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2038]
[Auto generated]
Number: [#2037]

**Comment by msi-b1** [comment]
[38;5;180mopenshift-python-wrapper[0m[pull_request][5acf-11ef-928b-1bfd966c7c54][PR 2037]: Closing issue for PR:  class-generator: Update and add cluster schema API files.
PR was closed.
