### ISSUE TITLE
types_generator - get value from the `type` key - 2041

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2042]
[Auto generated]
Number: [#2041]

**Comment by redhat-qe-bot2** [comment]
[38;5;25mopenshift-python-wrapper[0m[pull_request][5b3d-11ef-85b4-47f26f9d9c9a][PR 2041]: Closing issue for PR: types_generator - get value from the `type` key.
PR was closed.
