### ISSUE TITLE
updates to right import for virtual_machine_preference - 2051

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/openshift-python-wrapper#2052]
[Auto generated]
Number: [#2051]

**Comment by msi-b1** [comment]
[38;5;191mopenshift-python-wrapper[0m[pull_request][5c02-11ef-82f8-a6c7a698deb9][PR 2051]: Closing issue for PR: updates to right import for virtual_machine_preference.
PR was closed.
