### ISSUE TITLE
Update dict key and add comments in jinja - 2054

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2055]
[Auto generated]
Number: [#2054]

**Comment by redhat-qe-bot2** [comment]
[38;5;234mopenshift-python-wrapper[0m[pull_request][5d4a-11ef-8336-782bf2ddb0d6][PR 2054]: Closing issue for PR: Update dict key and add comments in jinja.
PR was closed.
