### ISSUE TITLE
class-generator: Support resources with same kind - 2060

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2061]
[Auto generated]
Number: [#2060]

**Comment by redhat-qe-bot2** [comment]
[38;5;29mopenshift-python-wrapper[0m[pull_request][5dfa-11ef-8918-a9e550c2c753][PR 2060]: Closing issue for PR: class-generator: Support resources with same kind.
PR was closed.
