### ISSUE TITLE
Update resources with multiple api groups and use `get` for `type` and `description` - 2067

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2068]
[Auto generated]
Number: [#2067]

**Comment by redhat-qe-bot2** [comment]
[38;5;84mopenshift-python-wrapper[0m[pull_request][606c-11ef-92e2-9fe874e8a333][PR 2067]: Closing issue for PR: Update resources with multiple api groups and use `get` for `type` and `description`.
PR was closed.
