### ISSUE TITLE
Get group from `x-kubernetes-group-version-kind` list - 2071

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2072]
[Auto generated]
Number: [#2071]

**Comment by redhat-qe-bot2** [comment]
[38;5;250mopenshift-python-wrapper[0m[pull_request][6088-11ef-9b2a-687b485f4de7][PR 2071]: Closing issue for PR: Get group from `x-kubernetes-group-version-kind` list.
PR was closed.
