### ISSUE TITLE
Add ServiceMeshMember, add another image resource and update description fetching - 2099

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2100]
[Auto generated]
Number: [#2099]

**Comment by msi-b1** [comment]
[38;5;226mopenshift-python-wrapper[0m[pull_request][75c5-11ef-81fd-276321fe4692][PR 2099]: Closing issue for PR: Add ServiceMeshMember, add another image resource and update description fetching.
PR was closed.
