### ISSUE TITLE
Pin kubernetes version to 27.x.x - 2118

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/openshift-python-wrapper#2119]
[Auto generated]
Number: [#2118]

**Comment by redhat-qe-bot1** [comment]
[38;5;242mopenshift-python-wrapper[0m[pull_request][78b0-11ef-8560-e6c37db0e865][PR 2118]: Closing issue for PR: Pin kubernetes version to 27.x.x.
PR was closed.
