### ISSUE TITLE
remove unused `ValueMismatch` class - 2141

### ISSUE THREAD

**Issue by rh-bot-1** [RedHatQE/openshift-python-wrapper#2142]
[Auto generated]
Number: [#2141]

**Comment by redhat-qe-bot1** [comment]
[38;5;162mopenshift-python-wrapper[0m[pull_request][8497-11ef-86c3-6044d0c8601d][PR 2141]: Closing issue for PR: remove unused `ValueMismatch` class.
PR was closed.
