### ISSUE TITLE
Resource creation - add an option to pass a complete resource dict  - 2148

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2149]
[Auto generated]
Number: [#2148]

**Comment by rh-bot-1** [comment]
[38;5;169mopenshift-python-wrapper[0m[pull_request][84c1-11ef-90b9-3cc3504b8ca8][PR 2148]: Closing issue for PR: Resource creation - add an option to pass a complete resource dict .
PR was closed.
