### ISSUE TITLE
class-generator: per required_args check for missing arg - 2157

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2158]
[Auto generated]
Number: [#2157]

**Comment by redhat-qe-bot2** [comment]
[38;5;228mopenshift-python-wrapper[0m[pull_request][86d8-11ef-9ee2-7f2e29dc5b5c][PR 2157]: Closing issue for PR: class-generator: per required_args check for missing arg.
PR was closed.
