### ISSUE TITLE
update README for failed install of openapi2jsonschema - 2203

### ISSUE THREAD

**Issue by rh-bot-1** [RedHatQE/openshift-python-wrapper#2204]
[Auto generated]
Number: [#2203]

**Comment by redhat-qe-bot1** [comment]
[38;5;101mopenshift-python-wrapper[0m[pull_request][678af100-ace2-11ef-9381-e5abfa901d70][PR 2203]: Closing issue for PR: update README for failed install of openapi2jsonschema.
PR was closed.
