### ISSUE TITLE
increase timeout and sleep value for retry_cluster_exceptions() in patch call - 2217

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2218]
[Auto generated]
Number: [#2217]

**Comment by redhat-qe-bot2** [comment]
[38;5;210mopenshift-python-wrapper[0m[pull_request][ec1e8360-b1be-11ef-951c-d92ab46ff75b][PR 2217]: Closing issue for PR: increase timeout and sleep value for retry_cluster_exceptions() in patch call.
PR was closed.
