### ISSUE TITLE
[v4.17] increase timeout and sleep value for retry_cluster_exceptions() in patch call - 2228

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/openshift-python-wrapper#2229]
[Auto generated]
Number: [#2228]

**Comment by rh-bot-1** [comment]
[38;5;113mopenshift-python-wrapper[0m[pull_request][4c975300-b8e2-11ef-95f4-4050460d24cb][PR 2228]: Closing issue for PR: [v4.17] increase timeout and sleep value for retry_cluster_exceptions() in patch call.
PR was closed.
