### ISSUE TITLE
Use testcontainers to test ocp_resources, add more test - 2232

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2233]
[Auto generated]
Number: [#2232]

**Comment by rh-bot-1** [comment]
[38;5;10mopenshift-python-wrapper[0m[pull_request][531b7110-bae1-11ef-985b-a8f41517a54c][PR 2232]: Closing issue for PR: Use testcontainers to test ocp_resources, add more test.
PR was closed.
