### ISSUE TITLE
Use `|` for typing instead of `Optional`, Fix imports  - 2238

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2239]
[Auto generated]
Number: [#2238]

**Comment by rh-bot-1** [comment]
[38;5;108mopenshift-python-wrapper[0m[pull_request][05e7fb30-bc66-11ef-9f84-216820c5ae00][PR 2238]: Closing issue for PR: Use `|` for typing instead of `Optional`, Fix imports .
PR was closed.
