### ISSUE TITLE
Deprecate `privileged_client`, use client. - 2242

### ISSUE THREAD

**Issue by rh-bot-1** [RedHatQE/openshift-python-wrapper#2243]
[Auto generated]
Number: [#2242]

**Comment by redhat-qe-bot2** [comment]
[38;5;23mopenshift-python-wrapper[0m[pull_request][1afe31d0-be12-11ef-9177-1fe91b557897][PR 2242]: Closing issue for PR: Deprecate `privileged_client`, use client..
PR was closed.
