### ISSUE TITLE
debug log would print raw data and readme is updated to reflect that - 2248

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-wrapper#2249]
[Auto generated]
Number: [#2248]

**Comment by redhat-qe-bot2** [comment]
[38;5;224mopenshift-python-wrapper[0m[pull_request][1cadb450-c138-11ef-8417-9791791dfba3][PR 2248]: Closing issue for PR: debug log would print raw data and readme is updated to reflect that.
PR was closed.
