### ISSUE TITLE
In wait_complete of VM restore and VM snaphot need to check also that RestoreInProgress and SnapshotInProgress is nil

### ISSUE THREAD

**Issue by jpeimer** [RedHatQE/openshift-python-wrapper#685]
**Describe the bug**
The current check is not enough and may cause test flakiness, so dev says we need to also check that 
RestoreInProgress is nil and
SnapshotInProgress is nil.

**Comment by myakove** [comment]
@jpeimer is this still needed? 
are you going to make the needed changes?

**Comment by jpeimer** [comment]
It was resolved by Dalia: https://github.com/RedHatQE/openshift-python-wrapper/pull/692
Thanks, I'm closing the issue.
